### ISSUE TITLE
librarian is not properly authenticating "<username>:<password>"

### ISSUE THREAD

**Issue by sroerick** [dloa/alexandria-librarian-old#20]
`getblockcount failed
Error getting json reply: Error sending json message: Post http://<username>:<password>@127.0.0.1:18322: dial tcp 127.0.0.1:18322: getsockopt: connection refused`

I think this issue is caused by not properly setting envvars.

I generally set using 
```export F_USER=<flouser>
export F_TOKEN=<flopassword>

```

Fixing this issue SHOULD allow libraryd to connect to florincoin. it currently does not appear to be

```

**Comment by luigiplr** [comment]
This is due to floincoin not being synced up yet. 

Adding to 0.0.2 milestone.

**Comment by luigiplr** [comment]
fixed.
