### ISSUE TITLE
need florincoin blockchain sync progress bar

### ISSUE THREAD

**Issue by DevonJames** [dloa/alexandria-librarian-old#24]
Get the Florincoin blockchain's current max block height:
`florincoin getpeerinfo`
you'll receive a few responses, usually around 8. Look at the `startingheight` fields and store the _max value_ as variable `current_block`. (Note, this was actually the current block when your wallet connected to that node, not this moment)

Get your local wallet's block count:
`getblockcount`
store as variable `wallet_block` 

Maths - `$wallet_block` / `$current_block` = ​_% Synced_​

**Comment by luigiplr** [comment]
Done.
