### ISSUE TITLE
Error localhost address already in use when starting IPFS

### ISSUE THREAD

**Issue by songproducer** [dloa/alexandria-librarian-old#41]
[ERROR] 12/17/2015, 3:29:03 AM Error: serveHTTPGateway: manet.Listen(/ip4/127.0.0.1/tcp/8080) failed: listen tcp4 127.0.0.1:8080: bind: address already in use

[INFO] 12/17/2015, 3:29:03 AM Killing : /Users/leotreasure/Library/Application Support/Alexandria_librarian/bin/ipfs --daemon
[INFO] 12/17/2015, 3:29:03 AM Terminated With Exit Code: 1

**Comment by luigiplr** [comment]
@songproducer is port `8080` actually already in use?

**Comment by songproducer** [comment]
Yes.

**Comment by luigiplr** [comment]
Ill be adding a option once preferences is made to change the IPFS port to hopefully negate such issues in the future.

**Comment by jaruba** [comment]
@luigiplr: be careful with that, the site checks for librarian on a specific port, so you gotta find a way to pass the port to the website if you change it.
